### PR TITLE
Run C32 results through procedures parser too, fixes #73

### LINKED ISSUE #73: Include C32 procedures from Results sections
Per https://github.com/blue-button/bluebutton.js/pull/72#issuecomment-26114114

### PR DESCRIPTION
**Pull request by thetylerhayes**
This runs both Results and Procedures through the C32 Procedures parser, because as #73 mentions sometimes Results sections contain Procedures too.

What a world.

### CODE REVIEW

**Comment by thetylerhayes** [comment]
`el2` isn't necessarily the most eloquent way to do this, but this does work when I test it. Open to alternatives.

**Comment by sankarravi** [comment]
Before diving into the implementation, did the procedures that appeared in the results sections in your files look to you like stuff that clinically belongs in the procedures section / is similar to the existing stuff in the procedures section? I was looking for an example of this in the sample C32 we have in the repo and above the one I found it says:
> HITSP/C83 requires Diagnostic Results to have both Procedure and Results, but gives no guidance as to how they should be related together. If Result requires a specimen, the Procedure to obtain the specimen could be under the specimen. This example simply groups a Procedure with the Results obtained from that Procedure. This is probably not the best way to do it, but satisfies the requirements of both IHE/PCC and HITSP/C83 for Diagnostic Results.

And the procedures I see in there are stuff like "Extract blood for CBC test" for a Hematology report. I.e., a method for the lab, rather than a documentation that some procedure (like a surgery or colonoscopy or something) was done for the patient. Is that consistent with what you're seeing, or are you seeing places where things that clearly belong in the procedures section were only included in association with a result?

On the implementation: wow, I'm not sure how this works! As far as I know, JavaScript doesn't have any support for tuples like this. Maybe Node implicitly constructs an array out of this? I do think it will probably fail in at least some browsers*.

If we decided to do this, I would suggest implementing this in c32/procedures.js instead. Something like:
```
var procedures = c32.section('procedures');
var results = c32.section('results'); // the results section can reference procedures too

function processProcedureEntry(entry) {
...
}

procedures.entries().each(processProcedureEntry);
results.entries().each(processProcedureEntry);
```

*Our test suite should help answer that. Now Travis is setup on the repo, so next time the branch is pushed, the tests will run. They'll almost certainly need to updated to pass, since this is going to change the expected JSON.

**Comment by sankarravi** [comment]
Ah, just read your full comment on #73.
> In other words: a results element would parent a bunch of test results (observation tags) and also one procedure. And the procedure would have the same details as the parenting results element itself.

If that's the case, do you think we should do extra work to include the results-procedures data in our procedures data? So far, it sounds more like a quirk of the C32 than useful data...

**Comment by thetylerhayes** [comment]
I'll wait to speak on all the technical stuff. Good thoughts, but we should nail down the what/why first.

> Is that consistent with what you're seeing, or are you seeing places where things that clearly belong in the procedures section were only included in association with a result?

Yep. Exactly that.

To be clear though, I can't say I'm seeing any consistent patterns yet. Sample C32 files around the Web are poorly put together and my own C32 records are just an n of 1.

> So far, it sounds more like a quirk of the C32 than useful data...

Yeah that's kind of my overall fear here. I don't have enough data to interpret any patterns in what I'm seeing. And even then to your point just reacting patterns is dangerous because no shortage of EMRs don't exactly follow the spec to the letter ;)

I'd prefer to have someone with more operating experience here. Maybe @jmandel has thoughts too.

Ultimately, for now, based on my comment...

> In other words: a results element would parent a bunch of test results (observation tags) and also one procedure. And the procedure would have the same details as the parenting results element itself.

... I'm comfortable/would prefer to not merge this yet. Because without attributes like devices/specimens, these so-called "procedures" aren't differentiated in any way from the title of the result itself. So other than data pedantry I don't see a strong reason to include these yet. (But, again, that's based on my limited sampling.)

**Comment by sankarravi** [comment]
Fair to close this / the associated issue then @thetylerhayes ?

**Pull request closed without merging**
